apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: userservice-canary
  namespace: bank
spec:
  hosts:
# For traffic routed to the accounts service ... 
  - accountsservice
  http:
# And for only the user endpoints...
  - match: 
    - uri:
        prefix: "/users"
# Send only 20% of those requests to the new user service. 
    route:
    - destination:
        host: userservice-java
      weight: 20
    - destination:
        host: accountsservice
      weight: 80